// <auto-generated />
using System;
using APIPhieuThu.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPhieuThu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231023180032_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPhieuThu.Entities.ChiTietPhieuThu", b =>
                {
                    b.Property<int>("ChiTietPhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhieuThuId"));

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int?>("PhieuThuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ChiTietPhieuThuId");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuThuId");

                    b.ToTable("ChiTietPhieuThu");
                });

            modelBuilder.Entity("APIPhieuThu.Entities.LoaiNguyenLieu", b =>
                {
                    b.Property<int>("LoaiNguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiNguyenLieuId"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiNguyenLieuId");

                    b.ToTable("LoaiNguyenLieu");
                });

            modelBuilder.Entity("APIPhieuThu.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuId"));

                    b.Property<string>("DVT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("LoaiNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguyenLieuId");

                    b.HasIndex("LoaiNguyenLieuId");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("APIPhieuThu.Entities.PhieuThu", b =>
                {
                    b.Property<int>("PhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuThuId"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("PhieuThuId");

                    b.ToTable("PhieuThu");
                });

            modelBuilder.Entity("APIPhieuThu.Entities.ChiTietPhieuThu", b =>
                {
                    b.HasOne("APIPhieuThu.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIPhieuThu.Entities.PhieuThu", "PhieuThu")
                        .WithMany("chiTietPhieuThus")
                        .HasForeignKey("PhieuThuId");

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuThu");
                });

            modelBuilder.Entity("APIPhieuThu.Entities.NguyenLieu", b =>
                {
                    b.HasOne("APIPhieuThu.Entities.LoaiNguyenLieu", "LoaiNguyenLieu")
                        .WithMany()
                        .HasForeignKey("LoaiNguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNguyenLieu");
                });

            modelBuilder.Entity("APIPhieuThu.Entities.PhieuThu", b =>
                {
                    b.Navigation("chiTietPhieuThus");
                });
#pragma warning restore 612, 618
        }
    }
}
